// <auto-generated />
using MSOrleansDemo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MSOrleansDemo.Migrations
{
    [DbContext(typeof(OrleansDemoDbContext))]
    [Migration("20230303165338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MSOrleansDemo.Context.AgreementState", b =>
                {
                    b.Property<string>("AgreementId")
                        .HasColumnType("text");

                    b.Property<string>("PdfFileLocation")
                        .HasColumnType("text");

                    b.Property<string>("SignerId")
                        .HasColumnType("text");

                    b.HasKey("AgreementId");

                    b.ToTable("AgreementStates");
                });
#pragma warning restore 612, 618
        }
    }
}
